language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2

env:
  matrix:
    - LARAVEL=5.7.*
    - LARAVEL=5.8.*

matrix:
  fast_finish: true
  allow_failures:
    - env: LARAVEL=5.8

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - travis_retry composer require "illuminate/contracts=${LARAVEL}" --dev --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit --verbose